In [1]:
import numpy as np
import pandas as pd

In [2]:
lista = [1,2,3,4,5,6,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)
type(arr)

numpy.ndarray

In [4]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 6, 7, 8, 9])

In [6]:
arr[0]

1

In [7]:
matriz[0]

array([1, 2, 3])

Se usa la coma para navegar entre las columnas y filas

In [8]:
matriz[0,2]

3

Podemos traer varios con un usando dos puntos, sino espefica un valor, significa que es de inicio a final.

In [9]:
arr[1:5]

array([2, 3, 4, 5])

In [10]:
arr[:]

array([1, 2, 3, 4, 5, 6, 6, 7, 8, 9])

Quiero todo el arreglo, pero de 3 en 3

In [11]:
arr[::3]

array([1, 4, 6, 9])

Podemos recorrer de forma inversa el array usando los valores negativos, es decir -(#de posiciones)

In [12]:
arr[-2]

8

En el caso de la matriz es muy similar, unicamente hay que recodar que se usa la coma para navegar entre filas y renglones

In [13]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

En numpy podemos concer el tipo de dato usando dtype.

In [14]:
arr.dtype

dtype('int64')

Además podemos cambiar el tipo de dato actual

In [15]:
arr = np.array(arr,dtype='float64')
arr.dtype

dtype('float64')

In [16]:
arr = arr.astype(np.int64)
arr.dtype

dtype('int64')

In [17]:
arr = arr.astype(np.int8)
arr.dtype

dtype('int8')

## Es importante tener en cuenta que los array de numpy, únicamente pueden tener un solo tipo de dato en su interior.

# Dimensiones

In [18]:
scalar = np.array(42)
scalar.ndim

0

In [19]:
vector = np.array([1,2,3])
vector.ndim

1

In [20]:
matriz = np.array([[1,2,3],[0,4,6]])
matriz.ndim

2

In [21]:
tensor = np.array([[[1,2,3],[0,4,6]],[[1,2,3],[0,4,6]]])
tensor.ndim

3

## Agregar o eliminar dimensiones

Definiremos un tensor, cuya dimensión desde el momento en que lo creamos, es 10.

In [22]:
dim10 = np.array([1,2,3], ndmin = 10)
print(dim10)
dim10.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [23]:
dim11 = np.expand_dims(dim10,axis=0)
print(dim11)
dim11.ndim

[[[[[[[[[[[1 2 3]]]]]]]]]]]


11

Para optimizar el número de dimensiones que usamos, podemos usar el siguiente comando, el cual se usa comunmente para reducir dimensiones.

In [24]:
dim1 = np.squeeze(dim11)
print(dim1)
dim1.ndim

[1 2 3]


1

# Creando arrays

In [25]:
#Sintaxis pura de python
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
#Usando numpy
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.zeros(3)

array([0., 0., 0.])

In [28]:
#Podemos pasar una tupla con la cantidad de filas
#y columnas que deseamos
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

De manera muy similar, existe la opción de crearlo con 1's

In [29]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Otra opción interesante es linspace, la cuál recibé como paramétros, el valor inicial, el valor final y la cantidad de números entre estos.

In [30]:
np.linspace(0,25,4)

array([ 0.        ,  8.33333333, 16.66666667, 25.        ])

Podemos crear una matriz identidad con eye

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Para generar números aleatorios, usamos la función rand()

In [32]:
np.random.rand(1)

array([0.14565927])

In [33]:
np.random.rand(2,4)

array([[0.38196392, 0.55405666, 0.72422978, 0.47001047],
       [0.38134292, 0.83843893, 0.81962757, 0.32490441]])

In [34]:
np.random.randint(1,15)

3

In [35]:
np.random.randint(1,100, (10,10))

array([[35, 98, 76, 73, 12, 52, 56, 86, 92, 35],
       [12, 87, 21, 66, 86, 19, 45, 66, 80, 72],
       [ 9, 92, 55, 56, 67, 41, 47, 31, 23, 14],
       [84, 89, 72, 56, 35, 67, 44,  5, 14, 16],
       [72, 92, 50,  5, 19, 20, 98, 46,  4, 22],
       [20, 47, 23, 16, 95, 94,  3, 25, 41, 78],
       [82, 69,  2, 40, 11, 80, 62,  6, 97, 82],
       [74, 47, 14, 69,  2, 97, 14, 37, 89, 28],
       [90, 92, 42, 38,  8, 77, 85, 38, 32, 93],
       [31, 89, 61, 92, 33, 23, 13,  5, 70, 50]])

# shape y reshape

Podemos conocer el tamaño de un array de la siguiente forma

In [36]:
arr = np.random.randint(1,10,(3,2))
print(arr)
arr.shape

[[9 8]
 [4 3]
 [3 8]]


(3, 2)

También podemos modificar su estructura si usamos el comando rshape()

In [37]:
arr.reshape(1,6)

array([[9, 8, 4, 3, 3, 8]])

In [38]:
arr.reshape(2,3)

array([[9, 8, 4],
       [3, 3, 8]])

Podemos cambiar la forma que hace está reestrucuración a los diferentes lenguajes de programación que existen o incluso a la forma en que esté optimizado en nuestra computadora

In [39]:
# La F es de fortran y en este lenguaje se 
# hace por columnas
np.reshape(arr,(2,3), 'F')

array([[9, 3, 3],
       [4, 8, 8]])

Si usamos la letra 'A', es como le indicamos que lo haga de la forma optimizado para nuestra pc

In [40]:
np.reshape(arr,(2,3), 'A')

array([[9, 8, 4],
       [3, 3, 8]])

In [41]:
# arr.reshape(3,3) Error

# Finciones principales de NumPy

In [42]:
arr.max()

9

Podemos conocer incluso el valor máximo por filas o columnas en matrices, simplemente recordar que el cero significa filas y el 1 columnas

In [43]:
matriz.max(0)

array([1, 4, 6])

Es posible conocer la diferencia entre el número mayor y el menor usando la función ptp()

In [44]:
print(arr)
arr.ptp()

[[9 8]
 [4 3]
 [3 8]]


6

In [45]:
np.percentile(arr,50)

6.0

In [46]:
arr = np.random.randint(1,10,(2,3))
arr = arr.reshape(1,6)
arr.sort()
arr

array([[1, 2, 4, 4, 8, 9]])

In [47]:
a = np.array([[1,2],[4,5]])
b = np.array([[7,8]])
np.concatenate((a,b),axis=0)


array([[1, 2],
       [4, 5],
       [7, 8]])

Podemos usar fácilmente la transpuesta de un vector, agregando .T

In [48]:
a = np.array([[1,2],[4,5]])
b = np.array([[7,8]])
np.concatenate((a,b.T),axis=1)

array([[1, 2, 7],
       [4, 5, 8]])

# Copy

In [49]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
trozo_de_arr = arr[0:6]
(trozo_de_arr)

array([0, 1, 2, 3, 4, 5])

In [51]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [52]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Dañanamos la estructura original porque sigue haciendo referencia al objecto padre, esto se puede solucionar usando el comando copy()

In [53]:
arr_copy = arr.copy()

In [54]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [55]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

En esta ocasión no se modifico el objeto padre porque ya no hace referencia a él, es decir que ocupa otro espacio en memoría.

# Condiciones

In [56]:
arr = np.linspace(1,10,10,dtype='int8')
print(arr)
indices_cond = arr > 5
indices_cond

[ 1  2  3  4  5  6  7  8  9 10]


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [57]:
arr[(indices_cond) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [58]:
arr[(indices_cond)]= 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [59]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

# Operaciones

In [60]:
lista = [1,2]
lista

[1, 2]

In [61]:
#Duplica la lista pero no múltiplica los elementos por 2
lista*2

[1, 2, 1, 2]

In [62]:
arr = np.arange(0,10)
arr2 = arr.copy()

In [63]:
print(arr)
arr *2
arr ** 3

[0 1 2 3 4 5 6 7 8 9]


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [64]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [65]:
print(np.matmul(arr.T, arr2))
arr.T @ arr2 #Lo mismo que arriba

285


285

# Series y DataFrames en pandas

In [66]:
psg_players=pd.Series(['Navas', 'Mbappe', 'Neymar', 'Mesi'],
         index = [1,7,5,10])
psg_players

1      Navas
7     Mbappe
5     Neymar
10      Mesi
dtype: object

In [67]:
dict = {1:'Navas',7:'Mbappe', 5: 'Neymar', 10: 'Messi'}
pd.Series(dict)

1      Navas
7     Mbappe
5     Neymar
10     Messi
dtype: object

In [68]:
psg_players[0:3]

1     Navas
7    Mbappe
5    Neymar
dtype: object

In [69]:
dict = {'Jugador': ['Navas', 'Mbappe', 'Neymar', 'Mesi'],
'Altura': [183.0, 170.0, 1.70, 165.0],
'Goles': [2,200,100,200]}

df_players =pd.DataFrame(dict, index = [1,7,5,10])

In [70]:
df_players.columns

Index(['Jugador', 'Altura', 'Goles'], dtype='object')

In [71]:
df_players.index

Int64Index([1, 7, 5, 10], dtype='int64')

# Leer archivos csv y JSON con pandas

In [72]:
df_books = pd.read_csv('bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv', sep=',', header = 0, names = ['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'])

In [73]:
df_books.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [74]:
df_books.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [75]:
pd.read_json('HPCharactersDataRaw.json')

Name                                               Link  \
0              Mrs. Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
1            Hannah Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
2            Abel Treetops  https://www.hp-lexicon.org/character/abel-tree...   
3         Euan Abercrombie  https://www.hp-lexicon.org/character/abercromb...   
4     Aberforth Dumbledore  https://www.hp-lexicon.org/character/dumbledor...   
...                    ...                                                ...   
1935        Georgi Zdravko  https://www.hp-lexicon.org/character/georgi-zd...   
1936                Zograf       https://www.hp-lexicon.org/character/zograf/   
1937                 Zonko        https://www.hp-lexicon.org/character/zonko/   
1938     Valentina Vázquez  https://www.hp-lexicon.org/character/valentina...   
1939         Zygmunt Budge  https://www.hp-lexicon.org/character/zygmunt-b...   

                                                  Descr  Gender Species/Race  \
0     Mrs. Abbott was the mother of Hannah Abbott, a...  Female        Witch   
1     Hannah Abbott is a Hufflepuff student in Harry...  Female        Witch   
2     Abel Treetops was a wizard from Cincinnati who...    Male       Wizard   
3     Euan Abercrombie was a small boy with prominen...    Male       Wizard   
4     Aberforth Dumbledore was a tall, thin, grumpy-...    Male       Wizard   
...                                                 ...     ...          ...   
1935  Georgi Zdravko played Keeper for the Bulgarian...    Male       Wizard   
1936  Zograf played Keeper for the Bulgarian Nationa...     NaN       Wizard   
1937  Founder(?) of Zonko’s Joke Shop. Possibly a re...     NaN      Unknown   
1938  Valentina Vázquez was President of the Argenti...  Female        Witch   
1939  Zygmunt Budge is considered to be one of the m...    Male       Wizard   

            Blood                 School  \
0     Muggle-born                Unknown   
1      Half-blood  Hogwarts - Hufflepuff   
2         Unknown                Unknown   
3         Unknown  Hogwarts - Gryffindor   
4      Half-blood     Hogwarts - Student   
...           ...                    ...   
1935      Unknown                Unknown   
1936      Unknown                Unknown   
1937      Unknown                Unknown   
1938      Unknown                Unknown   
1939      Unknown     Hogwarts - Student   

                                         Profession  
0                                           Unknown  
1                    Landlady of the Leaky Cauldron  
2                                           Unknown  
3                                           Unknown  
4                                            Barman  
...                                             ...  
1935                      Quidditch player (Seeker)  
1936                      Quidditch player (Keeper)  
1937                                        Unknown  
1938  President of the Argentinian Council of Magic  
1939    Potions Master, Potioneer, Inventor, Author  

[1940 rows x 8 columns]

In [76]:
pd.read_json('HPCharactersDataRaw.json', typ = 'Series')

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...                        
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina Vázquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

# Filtrando con loc (usas labels) y iloc (índices)

In [77]:
df_books[0:4]

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [78]:
df_books[['Name', 'Author','Year']]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  Year  
0                    JJ Smith  2016  
1                Stephen King  2011  
2          Jordan B. Peterson  2018  
3               George Orwell  2017  
4    National Geographic Kids  2019  
..                        ...   ...  
545               Jeff Kinney  2019  
546               Jen Sincero  2016  
547               Jen Sincero  2017  
548               Jen Sincero  2018  
549               Jen Sincero  2019  

[550 rows x 3 columns]

In [79]:
df_books.loc[:]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [80]:
df_books.loc[0:4]

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [81]:
df_books.loc[0:4, ['Name', 'Author']]

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [82]:
df_books.loc[:, ['Reviews']] * -1

Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [83]:
df_books.loc[1:1, ['Reviews']] 

Reviews
1     2052

In [84]:
df_books.loc[:, ['Author']] == 'JJ Smith'

Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

## iloc

In [85]:
df_books.iloc[:]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [86]:
df_books.iloc[:,0:3]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  
0                    JJ Smith          4.7  
1                Stephen King          4.6  
2          Jordan B. Peterson          4.7  
3               George Orwell          4.7  
4    National Geographic Kids          4.8  
..                        ...          ...  
545               Jeff Kinney          4.9  
546               Jen Sincero          4.7  
547               Jen Sincero          4.7  
548               Jen Sincero          4.7  
549               Jen Sincero          4.7  

[550 rows x 3 columns]

In [87]:
df_books.iloc[1,3] * - 1

-2052

In [88]:
df_books.iloc[:2,2:]

User Rating  Reviews  Price  Year        Genre
0          4.7    17350      8  2016  Non Fiction
1          4.6     2052     22  2011      Fiction

# Agregar o eliminar datos con Pandas

## Drop columns

In [89]:
df_books.drop('Genre',axis=1, inplace = True)

In [90]:
df_books = df_books.drop('Year',axis=1)

In [91]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8
1              11/22/63: A Novel  Stephen King          4.6     2052     22

In [92]:
del df_books['Price']
df_books.head(2)

Name        Author  User Rating  Reviews
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350
1              11/22/63: A Novel  Stephen King          4.6     2052

Para borrar filas es lo mismo pero con el axis = 0

In [93]:
df_books.drop(0,axis=0, inplace = True)
df_books.head(2)

Name              Author  User Rating  \
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   

   Reviews  
1     2052  
2    18979

In [94]:
df_books.head(2)

Name              Author  User Rating  \
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   

   Reviews  
1     2052  
2    18979

In [95]:
df_books.drop([1,2],axis=0, inplace = True)
df_books.head(2)

Name  \
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  
3             George Orwell          4.7    21424  
4  National Geographic Kids          4.8     7665

  Si solo se desea borrar de la salida, únicamente hay que quitar el paramétro inplace=True, para que este cambio no se permanente, además podemos usar range para eliminar multiples filas.

In [96]:
df_books.drop(range(3,10),axis=0).head(2)

Name            Author  \
10                          A Man Called Ove: A Novel   Fredrik Backman   
11  A Patriot's History of the United States: From...  Larry Schweikart   

    User Rating  Reviews  
10          4.6    23848  
11          4.6      460

## Agregando una nueva columna

In [97]:
df_books['Nueva_Columna'] = np.nan
df_books.head(2)

Name  \
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Nueva_Columna  
3             George Orwell          4.7    21424            NaN  
4  National Geographic Kids          4.8     7665            NaN

In [98]:
data = np.arange(0,df_books.shape[0])

In [99]:
df_books['Rango'] = data
df_books.head(-5)

Name  \
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
5        A Dance with Dragons (A Song of Ice and Fire)   
6    A Game of Thrones / A Clash of Kings / A Storm...   
7                       A Gentleman in Moscow: A Novel   
..                                                 ...   
540                                             Wonder   
541                                             Wonder   
542                                             Wonder   
543                                             Wonder   
544                                             Wonder   

                       Author  User Rating  Reviews  Nueva_Columna  Rango  
3               George Orwell          4.7    21424            NaN      0  
4    National Geographic Kids          4.8     7665            NaN      1  
5         George R. R. Martin          4.4    12643            NaN      2  
6         George R. R. Martin          4.7    19735            NaN      3  
7                 Amor Towles          4.7    19699            NaN      4  
..                        ...          ...      ...            ...    ...  
540             R. J. Palacio          4.8    21625            NaN    537  
541             R. J. Palacio          4.8    21625            NaN    538  
542             R. J. Palacio          4.8    21625            NaN    539  
543             R. J. Palacio          4.8    21625            NaN    540  
544             R. J. Palacio          4.8    21625            NaN    541  

[542 rows x 6 columns]

## Agregando rows

In [100]:
df_books.append(df_books.iloc[1:3])


/tmp/ipykernel_27164/1988966029.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_books.append(df_books.iloc[1:3])


Name  \
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
5        A Dance with Dragons (A Song of Ice and Fire)   
6    A Game of Thrones / A Clash of Kings / A Storm...   
7                       A Gentleman in Moscow: A Novel   
..                                                 ...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
4    5,000 Awesome Facts (About Everything!) (Natio...   
5        A Dance with Dragons (A Song of Ice and Fire)   

                       Author  User Rating  Reviews  Nueva_Columna  Rango  
3               George Orwell          4.7    21424            NaN      0  
4    National Geographic Kids          4.8     7665            NaN      1  
5         George R. R. Martin          4.4    12643            NaN      2  
6         George R. R. Martin          4.7    19735            NaN      3  
7                 Amor Towles          4.7    19699            NaN      4  
..                        ...          ...      ...            ...    ...  
547               Jen Sincero          4.7    14331            NaN    544  
548               Jen Sincero          4.7    14331            NaN    545  
549               Jen Sincero          4.7    14331            NaN    546  
4    National Geographic Kids          4.8     7665            NaN      1  
5         George R. R. Martin          4.4    12643            NaN      2  

[549 rows x 6 columns]

# Manejo de datos nulos

In [101]:
dict = {'Col1':[1,2,3,np.nan],
'Col2':[4, np.nan,6,7],
'Col3':['a','b','c', None]}

In [102]:
df = pd.DataFrame(dict)
df

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [103]:
df.isnull()

Col1   Col2   Col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [104]:
df.isnull()*1

Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [105]:
df.fillna('Missing')

Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [106]:
df.fillna(df.mean())

/tmp/ipykernel_27164/634187881.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean())


Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [107]:
df.interpolate()

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [108]:
df.dropna()

Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c

# Filtrado por condiciones

In [109]:
df_books = pd.read_csv('bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv', sep=',', header = 0, names = ['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'])
mayor_a_2016 = df_books['Year'] > 2016

In [110]:
df_books[mayor_a_2016]

Name  \
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
7                       A Gentleman in Moscow: A Novel   
8        A Higher Loyalty: Truth, Lies, and Leadership   
..                                                 ...   
544                                             Wonder   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
7                 Amor Towles          4.7    19699     15  2017      Fiction  
8                 James Comey          4.7     5983      3  2018  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
544             R. J. Palacio          4.8    21625      9  2017      Fiction  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[150 rows x 7 columns]

In [111]:
df_books[df_books['Genre'] == 'Fiction']

Name               Author  \
1                                    11/22/63: A Novel         Stephen King   
3                               1984 (Signet Classics)        George Orwell   
5        A Dance with Dragons (A Song of Ice and Fire)  George R. R. Martin   
6    A Game of Thrones / A Clash of Kings / A Storm...  George R. R. Martin   
7                       A Gentleman in Moscow: A Novel          Amor Towles   
..                                                 ...                  ...   
541                                             Wonder        R. J. Palacio   
542                                             Wonder        R. J. Palacio   
543                                             Wonder        R. J. Palacio   
544                                             Wonder        R. J. Palacio   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)          Jeff Kinney   

     User Rating  Reviews  Price  Year    Genre  
1            4.6     2052     22  2011  Fiction  
3            4.7    21424      6  2017  Fiction  
5            4.4    12643     11  2011  Fiction  
6            4.7    19735     30  2014  Fiction  
7            4.7    19699     15  2017  Fiction  
..           ...      ...    ...   ...      ...  
541          4.8    21625      9  2014  Fiction  
542          4.8    21625      9  2015  Fiction  
543          4.8    21625      9  2016  Fiction  
544          4.8    21625      9  2017  Fiction  
545          4.9     9413      8  2019  Fiction  

[240 rows x 7 columns]

In [112]:
genre_fiction = df_books['Genre'] == 'Fiction'

In [113]:
df_books[genre_fiction & mayor_a_2016]

Name             Author  \
3                               1984 (Signet Classics)      George Orwell   
7                       A Gentleman in Moscow: A Novel        Amor Towles   
10                           A Man Called Ove: A Novel    Fredrik Backman   
13                    A Wrinkle in Time (Time Quintet)  Madeleine L'Engle   
40            Brown Bear, Brown Bear, What Do You See?    Bill Martin Jr.   
..                                                 ...                ...   
509                              To Kill a Mockingbird         Harper Lee   
529  What Should Danny Do? (The Power to Choose Ser...          Adir Levy   
534                            Where the Crawdads Sing        Delia Owens   
544                                             Wonder      R. J. Palacio   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)        Jeff Kinney   

     User Rating  Reviews  Price  Year    Genre  
3            4.7    21424      6  2017  Fiction  
7            4.7    19699     15  2017  Fiction  
10           4.6    23848      8  2017  Fiction  
13           4.5     5153      5  2018  Fiction  
40           4.9    14344      5  2017  Fiction  
..           ...      ...    ...   ...      ...  
509          4.8    26234      7  2019  Fiction  
529          4.8     8170     13  2019  Fiction  
534          4.8    87841     15  2019  Fiction  
544          4.8    21625      9  2017  Fiction  
545          4.9     9413      8  2019  Fiction  

[65 rows x 7 columns]

In [114]:
df_books[~mayor_a_2016]

Name               Author  \
0                        10-Day Green Smoothie Cleanse             JJ Smith   
1                                    11/22/63: A Novel         Stephen King   
5        A Dance with Dragons (A Song of Ice and Fire)  George R. R. Martin   
6    A Game of Thrones / A Clash of Kings / A Storm...  George R. R. Martin   
9                            A Man Called Ove: A Novel      Fredrik Backman   
..                                                 ...                  ...   
540                                             Wonder        R. J. Palacio   
541                                             Wonder        R. J. Palacio   
542                                             Wonder        R. J. Palacio   
543                                             Wonder        R. J. Palacio   
546  You Are a Badass: How to Stop Doubting Your Gr...          Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
0            4.7    17350      8  2016  Non Fiction  
1            4.6     2052     22  2011      Fiction  
5            4.4    12643     11  2011      Fiction  
6            4.7    19735     30  2014      Fiction  
9            4.6    23848      8  2016      Fiction  
..           ...      ...    ...   ...          ...  
540          4.8    21625      9  2013      Fiction  
541          4.8    21625      9  2014      Fiction  
542          4.8    21625      9  2015      Fiction  
543          4.8    21625      9  2016      Fiction  
546          4.7    14331      8  2016  Non Fiction  

[400 rows x 7 columns]

# Funciones principales de Pandas

In [115]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


In [116]:
df_books.describe()

User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [117]:
df_books.memory_usage(deep=True)

Index            128
Name           59737
Author         39078
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          36440
dtype: int64

In [118]:
df_books['Author'].value_counts()

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

In [119]:
pd.DataFrame(df_books['Author'].value_counts())

Author
Jeff Kinney                             12
Gary Chapman                            11
Rick Riordan                            11
Suzanne Collins                         11
American Psychological Association      10
...                                    ...
Keith Richards                           1
Chris Cleave                             1
Alice Schertle                           1
Celeste Ng                               1
Adam Gasiewski                           1

[248 rows x 1 columns]

In [120]:
df_books.iloc[0]

Name           10-Day Green Smoothie Cleanse
Author                              JJ Smith
User Rating                              4.7
Reviews                                17350
Price                                      8
Year                                    2016
Genre                            Non Fiction
Name: 0, dtype: object

In [121]:
df_books = df_books.append(df_books.iloc[0])
df_books

/tmp/ipykernel_27164/2649199446.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_books = df_books.append(df_books.iloc[0])


Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  

[551 rows x 7 columns]

## Podemos borrar los duplicados y mantener el último

In [122]:
df_books = df_books.drop_duplicates(keep='last')
df_books

Name  \
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
5        A Dance with Dragons (A Song of Ice and Fire)   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
5         George R. R. Martin          4.4    12643     11  2011      Fiction  
..                        ...          ...      ...    ...   ...          ...  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  

[550 rows x 7 columns]

In [123]:
df_books.sort_values('Year')

Name                 Author  \
228        Mastering the Art of French Cooking, Vol. 2            Julia Child   
72       Diary of a Wimpy Kid: The Last Straw (Book 3)            Jeff Kinney   
96                                  Eclipse (Twilight)        Stephenie Meyer   
473                       The Twilight Saga Collection        Stephenie Meyer   
38           Breaking Dawn (The Twilight Saga, Book 4)        Stephenie Meyer   
..                                                 ...                    ...   
356  The Complete Ketogenic Diet for Beginners: You...              Amy Ramos   
475  The Unofficial Harry Potter Cookbook: From Cau...          Dinah Bucholz   
489                   The Wonderful Things You Will Be  Emily Winfield Martin   
522  Unicorn Coloring Book: For Kids Ages 4-8 (US E...             Silly Bear   
128  Girl, Stop Apologizing: A Shame-Free Plan for ...          Rachel Hollis   

     User Rating  Reviews  Price  Year        Genre  
228          4.8     2926     27  2009  Non Fiction  
72           4.8     3837     15  2009      Fiction  
96           4.7     5505     18  2009      Fiction  
473          4.7     3801     82  2009      Fiction  
38           4.6     9769     13  2009      Fiction  
..           ...      ...    ...   ...          ...  
356          4.3    13061      6  2019  Non Fiction  
475          4.7     9030     10  2019  Non Fiction  
489          4.9     8842     10  2019      Fiction  
522          4.8     6108      4  2019  Non Fiction  
128          4.6     7660     12  2019  Non Fiction  

[550 rows x 7 columns]

In [124]:
df_books.sort_values('Year', ascending = False)

Name             Author  \
130  Girl, Wash Your Face: Stop Believing the Lies ...      Rachel Hollis   
294  School Zone - Big Preschool Workbook - Ages 4 ...        School Zone   
534                            Where the Crawdads Sing        Delia Owens   
329  The 5 Love Languages: The Secret to Love that ...       Gary Chapman   
239  National Geographic Kids Why?: Over 1,111 Answ...      Crispin Boyer   
..                                                 ...                ...   
139  Good to Great: Why Some Companies Make the Lea...        Jim Collins   
60   Dead And Gone: A Sookie Stackhouse Novel (Sook...   Charlaine Harris   
512                             True Compass: A Memoir  Edward M. Kennedy   
513               Twilight (The Twilight Saga, Book 1)    Stephenie Meyer   
498  Three Cups of Tea: One Man's Mission to Promot...     Greg Mortenson   

     User Rating  Reviews  Price  Year        Genre  
130          4.6    22288     12  2019  Non Fiction  
294          4.8    23047      6  2019  Non Fiction  
534          4.8    87841     15  2019      Fiction  
329          4.8    25554      8  2019  Non Fiction  
239          4.8     5347     16  2019  Non Fiction  
..           ...      ...    ...   ...          ...  
139          4.5     3457     14  2009  Non Fiction  
60           4.6     1541      4  2009      Fiction  
512          4.5      438     15  2009  Non Fiction  
513          4.7    11676      9  2009      Fiction  
498          4.3     3319     11  2009  Non Fiction  

[550 rows x 7 columns]

# Group by

Básicamente es agrupar por una característica de interés y a este agrupamiento se le puede aplicar funciones de agregación.

In [125]:
df_books.groupby('Author').count()

Name  User Rating  Reviews  Price  Year  Genre
Author                                                                    
Abraham Verghese               2            2        2      2     2      2
Adam Gasiewski                 1            1        1      1     1      1
Adam Mansbach                  1            1        1      1     1      1
Adir Levy                      1            1        1      1     1      1
Admiral William H. McRaven     1            1        1      1     1      1
...                          ...          ...      ...    ...   ...    ...
Walter Isaacson                3            3        3      3     3      3
William Davis                  2            2        2      2     2      2
William P. Young               2            2        2      2     2      2
Wizards RPG Team               3            3        3      3     3      3
Zhi Gang Sha                   2            2        2      2     2      2

[248 rows x 6 columns]

In [126]:
df_books.groupby('Author').mean()

User Rating       Reviews      Price         Year
Author                                                                       
Abraham Verghese               4.600000   4866.000000  11.000000  2010.500000
Adam Gasiewski                 4.400000   3113.000000   6.000000  2017.000000
Adam Mansbach                  4.800000   9568.000000   9.000000  2011.000000
Adir Levy                      4.800000   8170.000000  13.000000  2019.000000
Admiral William H. McRaven     4.700000  10199.000000  11.000000  2017.000000
...                                 ...           ...        ...          ...
Walter Isaacson                4.566667   6222.666667  20.333333  2013.333333
William Davis                  4.400000   7497.000000   6.000000  2012.500000
William P. Young               4.600000  19720.000000   8.000000  2013.000000
Wizards RPG Team               4.800000  16990.000000  27.000000  2018.000000
Zhi Gang Sha                   4.600000    128.500000  11.500000  2011.000000

[248 rows x 4 columns]

In [127]:
df_books.groupby('Author').min()

Name  \
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                            User Rating  Reviews  Price  Year        Genre  
Author                                                                      
Abraham Verghese                    4.6     4866     11  2010      Fiction  
Adam Gasiewski                      4.4     3113      6  2017  Non Fiction  
Adam Mansbach                       4.8     9568      9  2011      Fiction  
Adir Levy                           4.8     8170     13  2019      Fiction  
Admiral William H. McRaven          4.7    10199     11  2017  Non Fiction  
...                                 ...      ...    ...   ...          ...  
Walter Isaacson                     4.5     3014     20  2011  Non Fiction  
William Davis                       4.4     7497      6  2012  Non Fiction  
William P. Young                    4.6    19720      8  2009      Fiction  
Wizards RPG Team                    4.8    16990     27  2017      Fiction  
Zhi Gang Sha                        4.6       37      6  2009  Non Fiction  

[248 rows x 6 columns]

Es importante notar que la característica que elegimos, se convierte en el index

In [128]:
df_books.groupby('Author').sum().loc['William P. Young']

User Rating        9.2
Reviews        39440.0
Price             16.0
Year            4026.0
Name: William P. Young, dtype: float64

In [129]:
df_books.groupby('Author').sum().reset_index()

Author  User Rating  Reviews  Price  Year
0              Abraham Verghese          9.2     9732     22  4021
1                Adam Gasiewski          4.4     3113      6  2017
2                 Adam Mansbach          4.8     9568      9  2011
3                     Adir Levy          4.8     8170     13  2019
4    Admiral William H. McRaven          4.7    10199     11  2017
..                          ...          ...      ...    ...   ...
243             Walter Isaacson         13.7    18668     61  6040
244               William Davis          8.8    14994     12  4025
245            William P. Young          9.2    39440     16  4026
246            Wizards RPG Team         14.4    50970     81  6054
247                Zhi Gang Sha          9.2      257     23  4022

[248 rows x 5 columns]

In [130]:
df_books.groupby('Author').agg(['min','max'])

Name  \
                                                                          min   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                                                                               \
                                                                          max   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min   
Author                                                                       
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010   
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017   
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011   
Adir Levy                          4.8  4.8    8170   8170    13  13  2019   
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017   
...                                ...  ...     ...    ...   ...  ..   ...   
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011   
William Davis                      4.4  4.4    7497   7497     6   6  2012   
William P. Young                   4.6  4.6   19720  19720     8   8  2009   
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017   
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009   

                                        Genre               
                             max          min          max  
Author                                                      
Abraham Verghese            2011      Fiction      Fiction  
Adam Gasiewski              2017  Non Fiction  Non Fiction  
Adam Mansbach               2011      Fiction      Fiction  
Adir Levy                   2019      Fiction      Fiction  
Admiral William H. McRaven  2017  Non Fiction  Non Fiction  
...                          ...          ...          ...  
Walter Isaacson             2017  Non Fiction  Non Fiction  
William Davis               2013  Non Fiction  Non Fiction  
William P. Young            2017      F

In [131]:
df_books.head(2)

Name              Author  User Rating  \
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   

   Reviews  Price  Year        Genre  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction

In [132]:
df_books.groupby('Author').agg({'Reviews': ['min','max'], 'User Rating': 'sum'})

Reviews        User Rating
                               min    max         sum
Author                                               
Abraham Verghese              4866   4866         9.2
Adam Gasiewski                3113   3113         4.4
Adam Mansbach                 9568   9568         4.8
Adir Levy                     8170   8170         4.8
Admiral William H. McRaven   10199  10199         4.7
...                            ...    ...         ...
Walter Isaacson               3014   7827        13.7
William Davis                 7497   7497         8.8
William P. Young             19720  19720         9.2
Wizards RPG Team             16990  16990        14.4
Zhi Gang Sha                    37    220         9.2

[248 rows x 3 columns]

In [133]:
df_books.groupby(['Author', 'Year']).count()

Name  User Rating  Reviews  Price  Genre
Author           Year                                          
Abraham Verghese 2010     1            1        1      1      1
                 2011     1            1        1      1      1
Adam Gasiewski   2017     1            1        1      1      1
Adam Mansbach    2011     1            1        1      1      1
Adir Levy        2019     1            1        1      1      1
...                     ...          ...      ...    ...    ...
Wizards RPG Team 2017     1            1        1      1      1
                 2018     1            1        1      1      1
                 2019     1            1        1      1      1
Zhi Gang Sha     2009     1            1        1      1      1
                 2013     1            1        1      1      1

[493 rows x 5 columns]

# Combinando DataFrames

In [134]:
df1 = pd.DataFrame({'A':['A0', 'A1', 'A2','A3'],
        'B':['B0', 'B1', 'B2','B3'],
	'C':['C0', 'C1', 'C2','C3'],
	'D':['D0', 'D1', 'D2','D3']})


df2 = pd.DataFrame({'A':['A4', 'A5', 'A6','A7'],
	'B':['B4', 'B5', 'B6','B7'],
	'C':['C4', 'C5', 'C6','C7'],
	'D':['D4', 'D5', 'D6','D7']})

In [135]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [136]:
df2

A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

## Concat

In [137]:
pd.concat([df1,df2], ignore_index=True) #Por defecto lo hace con axis=0

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [138]:
pd.concat([df1,df2], axis=1) 

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

## Merge

In [139]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [140]:
izq

key   A   B
0  k0  A0  B0
1  k1  A1  B1
2  k2  A2  B2
3  k3  A3  B3

In [141]:
der

key   C   D
0  k0  C0  D0
1  k1  C1  D1
2  k2  C2  D2
3  k3  C3  D3

In [142]:
izq.merge(der, on = 'key')

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [143]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key_2' : ['k0', 'k1', 'k2','k3'],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [144]:
izq.merge(der, left_on = 'key', right_on = 'key_2')

key   A   B key_2   C   D
0  k0  A0  B0    k0  C0  D0
1  k1  A1  B1    k1  C1  D1
2  k2  A2  B2    k2  C2  D2
3  k3  A3  B3    k3  C3  D3

In [145]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key_2' : ['k0', 'k1', 'k2',np.nan],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [146]:
der

key_2   C   D
0    k0  C0  D0
1    k1  C1  D1
2    k2  C2  D2
3   NaN  C3  D3

In [147]:
izq.merge(der, left_on = 'key', right_on = 'key_2')

key   A   B key_2   C   D
0  k0  A0  B0    k0  C0  D0
1  k1  A1  B1    k1  C1  D1
2  k2  A2  B2    k2  C2  D2

In [148]:
izq.merge(der, left_on = 'key', right_on = 'key_2', how = 'right')

key    A    B key_2   C   D
0   k0   A0   B0    k0  C0  D0
1   k1   A1   B1    k1  C1  D1
2   k2   A2   B2    k2  C2  D2
3  NaN  NaN  NaN   NaN  C3  D3

In [149]:
izq.merge(der, left_on = 'key', right_on = 'key_2', how = 'left')

key   A   B key_2    C    D
0  k0  A0  B0    k0   C0   D0
1  k1  A1  B1    k1   C1   D1
2  k2  A2  B2    k2   C2   D2
3  k3  A3  B3   NaN  NaN  NaN

In [150]:
izq.merge(der, left_on = 'key', right_on = 'key_2', how = 'outer')

key    A    B key_2    C    D
0   k0   A0   B0    k0   C0   D0
1   k1   A1   B1    k1   C1   D1
2   k2   A2   B2    k2   C2   D2
3   k3   A3   B3   NaN  NaN  NaN
4  NaN  NaN  NaN   NaN   C3   D3

# Join - index match

In [151]:
izq = pd.DataFrame({'A': ['A0','A1','A2'],
  'B':['B0','B1','B2']},
  index=['k0','k1','k2'])

der =pd.DataFrame({'C': ['C0','C1','C2'],
  'D':['D0','D1','D2']},
  index=['k0','k2','k3']) 

In [152]:
izq.join(der) #por defecto es left

A   B    C    D
k0  A0  B0   C0   D0
k1  A1  B1  NaN  NaN
k2  A2  B2   C1   D1

In [153]:
izq.join(der, how = 'inner')

A   B   C   D
k0  A0  B0  C0  D0
k2  A2  B2  C1  D1

In [154]:
izq.join(der, how = 'left')

A   B    C    D
k0  A0  B0   C0   D0
k1  A1  B1  NaN  NaN
k2  A2  B2   C1   D1

In [155]:
izq.join(der, how = 'right')

A    B   C   D
k0   A0   B0  C0  D0
k2   A2   B2  C1  D1
k3  NaN  NaN  C2  D2

In [156]:
izq.join(der, how = 'outer')

A    B    C    D
k0   A0   B0   C0   D0
k1   A1   B1  NaN  NaN
k2   A2   B2   C1   D1
k3  NaN  NaN   C2   D2

# Pivot table

transforma los valores de determinadas columnas o filas en los índices de un nuevo DataFrame, y la intersección de estos es el valor resultante

In [157]:
df_books.head()

Name  \
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   
5      A Dance with Dragons (A Song of Ice and Fire)   

                     Author  User Rating  Reviews  Price  Year        Genre  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction  
5       George R. R. Martin          4.4    12643     11  2011      Fiction

In [158]:
df_books.pivot_table(index='Author', columns='Genre', values = 'User Rating')

Genre                       Fiction  Non Fiction
Author                                          
Abraham Verghese                4.6          NaN
Adam Gasiewski                  NaN     4.400000
Adam Mansbach                   4.8          NaN
Adir Levy                       4.8          NaN
Admiral William H. McRaven      NaN     4.700000
...                             ...          ...
Walter Isaacson                 NaN     4.566667
William Davis                   NaN     4.400000
William P. Young                4.6          NaN
Wizards RPG Team                4.8          NaN
Zhi Gang Sha                    NaN     4.600000

[248 rows x 2 columns]

In [159]:
df_books.pivot_table(index='Genre',columns='Year', values='User Rating',aggfunc='sum')

Year          2009   2010   2011   2012   2013   2014   2015   2016   2017  \
Genre                                                                        
Fiction      110.2   92.3   97.0   94.4  109.1  134.3   79.1   89.6  113.7   
Non Fiction  119.0  135.6  130.9  132.2  118.6   96.8  153.3  144.3  119.3   

Year          2018   2019  
Genre                      
Fiction       99.5   96.4  
Non Fiction  133.9  140.6

In [160]:
df_books.groupby(['Genre', 'Year']).sum() #No tiene relación con pivot table, solo quería ver la diferencia.

User Rating  Reviews  Price
Genre       Year                             
Fiction     2009        110.2   156824    374
            2010         92.3   168185    194
            2011         97.0   217041    244
            2012         94.4   417821    258
            2013        109.1   479684    257
            2014        134.3   562103    295
            2015         79.1   403004    159
            2016         89.6   371702    240
            2017        113.7   350684    212
            2018         99.5   266919    184
            2019         96.4   370143    187
Non Fiction 2009        119.0    78682    396
            2010        135.6   105796    480
            2011        130.9   188000    511
            2012        132.2   236725    507
            2013        118.6   175223    473
            2014         96.8   230894    437
            2015        153.3   308665    362
            2016        144.3   338098    419
            2017        119.3   293736    357
            2018        133.9   429602    342
            2019        140.6   424774    317

## Melt

Tomas las columnas del DataFrame y las pasa a filas, con dos nuevas columnas para especificar la antigual columna y el valor que traía.

In [161]:
df_books[['Name','Genre']].head(5)

Name        Genre
1                                  11/22/63: A Novel      Fiction
2            12 Rules for Life: An Antidote to Chaos  Non Fiction
3                             1984 (Signet Classics)      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  Non Fiction
5      A Dance with Dragons (A Song of Ice and Fire)      Fiction

In [162]:
df_books[['Name','Genre']].head(5).melt()

variable                                              value
0     Name                                  11/22/63: A Novel
1     Name            12 Rules for Life: An Antidote to Chaos
2     Name                             1984 (Signet Classics)
3     Name  5,000 Awesome Facts (About Everything!) (Natio...
4     Name      A Dance with Dragons (A Song of Ice and Fire)
5    Genre                                            Fiction
6    Genre                                        Non Fiction
7    Genre                                            Fiction
8    Genre                                        Non Fiction
9    Genre                                            Fiction

In [163]:
df_books.melt(id_vars='Year',value_vars='Genre')

Year variable        value
0    2011    Genre      Fiction
1    2018    Genre  Non Fiction
2    2017    Genre      Fiction
3    2019    Genre  Non Fiction
4    2011    Genre      Fiction
..    ...      ...          ...
545  2016    Genre  Non Fiction
546  2017    Genre  Non Fiction
547  2018    Genre  Non Fiction
548  2019    Genre  Non Fiction
549  2016    Genre  Non Fiction

[550 rows x 3 columns]

# Apply

In [164]:
def two_times(value):
    return value * 2

In [165]:
df_books['Rating 2'] = df_books['User Rating'].apply(two_times)

/tmp/ipykernel_27164/1644985569.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_books['Rating 2'] = df_books['User Rating'].apply(two_times)


In [166]:
df_books.head()

Name  \
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   
5      A Dance with Dragons (A Song of Ice and Fire)   

                     Author  User Rating  Reviews  Price  Year        Genre  \
1              Stephen King          4.6     2052     22  2011      Fiction   
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3             George Orwell          4.7    21424      6  2017      Fiction   
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction   
5       George R. R. Martin          4.4    12643     11  2011      Fiction   

   Rating 2  
1       9.2  
2       9.4  
3       9.4  
4       9.6  
5       8.8

In [167]:
df_books['Rating 2'] = df_books['User Rating'].apply(lambda x: x*3)
df_books.head()

/tmp/ipykernel_27164/2554134135.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_books['Rating 2'] = df_books['User Rating'].apply(lambda x: x*3)


Name  \
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   
5      A Dance with Dragons (A Song of Ice and Fire)   

                     Author  User Rating  Reviews  Price  Year        Genre  \
1              Stephen King          4.6     2052     22  2011      Fiction   
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3             George Orwell          4.7    21424      6  2017      Fiction   
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction   
5       George R. R. Martin          4.4    12643     11  2011      Fiction   

   Rating 2  
1      13.8  
2      14.1  
3      14.1  
4      14.4  
5      13.2

In [168]:
df_books['Rating 2'] = df_books.apply(lambda x: x['User Rating']* 2 if x['Genre'] == 'Fiction' else x['User Rating'],axis=1)

/tmp/ipykernel_27164/853077269.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_books['Rating 2'] = df_books.apply(lambda x: x['User Rating']* 2 if x['Genre'] == 'Fiction' else x['User Rating'],axis=1)


In [169]:
df_books.head()

Name  \
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   
5      A Dance with Dragons (A Song of Ice and Fire)   

                     Author  User Rating  Reviews  Price  Year        Genre  \
1              Stephen King          4.6     2052     22  2011      Fiction   
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3             George Orwell          4.7    21424      6  2017      Fiction   
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction   
5       George R. R. Martin          4.4    12643     11  2011      Fiction   

   Rating 2  
1       9.2  
2       4.7  
3       9.4  
4       4.8  
5       8.8